[package]
name = "ascii-beta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.1"
image = "0.24.9"
terminal_size = "0.3.0"
